// tag::FEEDBACK[]
:filename: 01-basics/02-timing-didactics-and-more.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
=== Dauer, Didaktik und weitere Details

Die unten genannten Zeiten sind Empfehlungen. Die Dauer einer Schulung zum Modul {curriculum-short} sollte mindestens **?** Tage betragen, kann aber länger sein. Anbieter können sich durch Dauer, Didaktik, Art- und Aufbau der Übungen sowie der detaillierten Kursgliederung voneinander unterscheiden. Insbesondere die Art der Beispiele und Übungen lässt der Lehrplan komplett offen.

Lizenzierte Schulungen zu {curriculum-short} tragen zur Zulassung zur abschließenden Advanced Level Zertifizierungsprüfung folgende Punkte (Credit Points) bei:
 
Methodische Kompetenz:	**?** Punkte +
Technische Kompetenz:		**?** Punkte +
Kommunikative Kompetenz:	**?** Punkte

// end::DE[]

// tag::EN[]
T.B.D
// end::EN[]

// tag::REMARK[]
[IMPORTANT]
====
Bitte die Anzahl der Tage sowie der erreichbaren Punkte oben bei den **?** einsetzen.
====
// end::REMARK[]
