= Template for https://isaqb.org[iSAQB] Advanced Level Curricula

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
*DRAFT* version!!

image:https://travis-ci.org/isaqb-org/advanced-template.svg?branch=master["Build Status", link="https://travis-ci.org/isaqb-org/advanced-template"]
image:https://img.shields.io/github/last-commit/isaqb-org/advanced-template/master.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/advanced-template.svg["Contributors",link="https://github.com/isaqb-org/advanced-template/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/advanced-template.svg["Issues",link="https://github.com/isaqb-org/advanced-template/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/advanced-template.svg["Issues closed",link="https://github.com/isaqb-org/advanced-template/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains a template for iSAQB Advanced Level *curricula* in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to use this template

1. clone or download - but include the submodule:
+
--
[source,shell]
----
git clone git@github.com/username/repository.git --recursive
----
--
2. build it with gradle
3. look into the file `build.gradle` to see what attributes you may configure. Watch for:
** The `language` attribute, it can be DE, EN or DE;EN
** The output formats called `backends` (pdf and/or html5)
** The document version

== How to write iSAQB Advanced Level Curricula with AsciiDoc

=== Requirements and (our) solutions

[cols="1,2a",options="header"]
|===
|Requirement
|Solution

|Visually appealing pdf output
|We created an iSAQB pdf theme, located under the `/style` directory. The original is maintained in the `adoc2pdf` repository.

|Multiple people contribute content, review and comment
|highly modularized content: Small chunks, like learning-goals or subsections, are contained in their own asciidoc-files.

|Multiple languages, at least EN and DE (i18n)
|Every piece of text is enclosed in _tags_ like `tag::EN[]` The build process collects all parts for the desired language.

|Authors want to comment on specific parts of the text
|You can create a comment within every single adoc file by writing:

[source,asciidoc]
----
  // tag::REMARK[]
  your comment goes here, with all styling and formatting options.
  // end::REMARK[]
----

|Simple conversion from asciidoc to pdf (and html)
|There are several options available:

* Gradle based build, requiring a local Java runtime.
* Docker based build, requiring a local Docker installation
|===

- - -

**TODO:** Add explanation for keywords and general procedure when creating a new Advanced Level Curriculum.

- - -

=== How to organize files?

==== Prerequisite: AsciiDoc include
You should know some details about the AsciiDoc include statement.

If the Asciidoctor processor encounters a statement like the one below:

[source,asciidoc]
----
   include::directory/file.adoc[]
----

It will replace this include statement with the contents of `file.adoc`. That's easy and straightforward.

But there's more. We can tell AsciiDoc what parts of a file shall be included via the `tag` syntax. See below:

[source,asciidoc]
----
   include::directory/file.adoc[tags=X42]
----

Now AsciiDoctor will include everything from `file.adoc` which is contained between the opening and closing of tag `X42`. Let's look into our `file.adoc`:

[source,asciidoc]
----
some content that will be ignored...

   // tag::X42[]
   this content will be included with `include::directory/file.adoc[tags=X42]`
   // end::X42[]

and this content will be ignored again

   // tag::REMARK[]
   a comment from a reviewer that should be handled later
   // end::REMARK[]
----

You are thinking of using tags for i18n languages? Well done...


Now we're going one final step: We can enhance the include statement by *several* tags, so we can include multiple parts of a single file. I'll show the syntax and you know what I mean:

[source,asciidoc]
----
   include::directory/file.adoc[tags=X42;REMARK]
----

As you imagined, now both X42 and REMARK-tagged content will be included in the output.

=== Content and Structure files
As we are writing i18n we need to strictly distiguish between two
kind of files:

* *content* files, they contain text, tables or diagrams that shall be included in the output.
* *structure* files, containing only include-statements, configuration information. Structure files include both content-files and other structure files.

For content files, specific parts will be included via the tag-syntax described above.
For that purpose we define a variable named `include_configuration` in the file `config/setup.adoc`.

==== Structure File Example

File `advanced-curriculum.adoc` (excerpts):

[source,asciidoc]
----
= Template Curriculum: CPSA Certified Professional for Software Architecture®
:doctype: book

include::config/setup.adoc[]  // // <1>

:document-version: 2.0-DRAFT 2019 // //<2>

:sectnums!: // // <3>
include::00-preamble/copyright.adoc[{include_configuration}] // // <4>

<<< // // <5>
:toc:

<<<
:sectnums!:
include::00-preamble/00-introduction.adoc[] // //<6>

----

1. we propose to put asciidoc configuration in this special file (`setup.adoc`)
2. you can set a version, but may override in the build process
3. you can turn section numbering on and off (here: off)
4. this includes parts of the copyright.adoc file.
5. The `<<<` will create a pagebreak in pdf's.
6. include the whole file 00-introduction.adoc


=== Suggestions

TBD.

== How to build the documents

Prerequisite: You need a Java Runtime(tm) installed.

You build the output documents with gradle. That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration. 

In case you want to change that, adjust the following part of `build.gradle`:

[source,groovy]
----
task buildDocs {
  group 'Documentation'
  description 'Grouping task for generating all languages in several formats'
  dependsOn "renderNoRemarksDE", "renderNoRemarksEN", "renderWithRemarksDE_EN"
}
----

In the "renderNoRemarksDE" certain attributes (aka variables) are defined that configure the corresponding output. 


=== Legacy build
There is a Docker-based build available in https://github.com/isaqb-org/adoc2pdf[its own repository], in case you cannot build with gradle.


== Maintainers

This repository is currently maintained by Benjamin Wolf.
It was forked from https://github.com/isaqb-org/curriculum-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

[IMPORTANT]
====
THIS IS COPYRIGHTED WORK.

© (Copyright), https://isaqb.org[International Software Architecture Qualification Board e. V.]
(iSAQB® e. V.) 2009-2019
====

[IMPORTANT]
====
YOU NEED TO CHANGE that copyright for your REAL document!
====

The curriculum may only be used subject to the following conditions:

1. You wish to obtain the CPSA Certified Professional for Software Architecture Foundation Level® certificate. For the purpose of obtaining the certificate, it shall be permitted to use these text documents and/or curricula by creating working copies for your own computer. If any other use of documents and/or curricula is intended, for instance for their dissemination to third parties, for advertising etc., please write to contact@isaqb.org to enquire whether this is permitted. A separate license agreement would then have to be entered into.

2. If you are a trainer, training provider or training organizer, it shall be possible for you to use the documents and/or curricula once you have obtained a usage license.
Please address any enquiries to contact@isaqb.org. License agreements with comprehensive provisions for all aspects exist.

3. If you fall neither into category 1 nor category 2, but would like to use these documents and/or curricula nonetheless, please also contact the iSAQB e. V. by writing to contact@isaqb.org. You will then be informed about the possibility of acquiring relevant licenses through existing license agreements, allowing you to obtain your desired usage authorizations.

We stress that, as a matter of principle, this curriculum is protected by copyright.

The International Software Architecture Qualification Board e. V. (iSAQB® e. V.) has exclusive entitlement to these copyrights.

The abbreviation "e. V." is part of the iSAQB's official name and stands for "eingetragener Verein" (registered association), which describes its status as a legal entity according to German law.
 
