= Template for https://isaqb.org[iSAQB] Curricula

*DRAFT* version!!

This repository contains a template for iSAQB *curricula* in AsciiDoc. 

This is <<copyrighted,copyrighted work>>.

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to use this template

1. clone or download
2. build it with gradle
3. look into the file `build.gradle` to see what attributes you may configure.

== How to write iSAQB Curricula with AsciiDoc

=== Requirements and (our) solutions

[cols="1,2a",options="header"]
|===
|Requirement
|Solution

|Visually appealing pdf output
|We created an iSAQB pdf theme, located under the `/style` directory. The original is maintained in the `adoc2pdf` repository.

|Multiple people contribute content, review and comment
|highly modularized content: Small chunks, like learning-goals or subsections, are contained in their own asciidoc-files.

|Multiple languages, at least EN and DE (i18n)
|Every piece of text is enclosed in _tags_ like `tag::EN[]` The build process collects all parts for the desired language.

|Authors want to comment on specific parts of the text
|You can create a comment within every single adoc file by writing:

[source,asciidoc]
----
  // tag::REMARK[]
  your comment goes here, with all styling and formatting options.
  // end::REMARK[]
----

|Simple conversion from asciidoc to pdf (and html)
|There are several options available:

* Gradle based build, requiring a local Java runtime.
* Docker based build, requiring a local Docker installation
|===

=== How to organize files?

=== How to build (aka: how to convert asciidoc to pdf)?

== Maintainers

This repository is currently maintained by Gernot Starke.


[[copyrighted]]
== Licensing and Copyright

[IMPORTANT]
====
THIS IS COPYRIGHTED WORK.

© (Copyright), https://isaqb.org[International Software Architecture Qualification Board e. V.]
(iSAQB® e. V.) 2009-2019
====

[IMPORTANT]
====
YOU NEED TO CHANGE that copyright for your REAL document!
====

The curriculum may only be used subject to the following conditions:

1. You wish to obtain the CPSA Certified Professional for Software Architecture Foundation Level® certificate. For the purpose of obtaining the certificate, it shall be permitted to use these text documents and/or curricula by creating working copies for your own computer. If any other use of documents and/or curricula is intended, for instance for their dissemination to third parties, for advertising etc., please write to contact@isaqb.org to enquire whether this is permitted. A separate license agreement would then have to be entered into.

2. If you are a trainer, training provider or training organizer, it shall be possible for you to use the documents and/or curricula once you have obtained a usage license.
Please address any enquiries to contact@isaqb.org. License agreements with comprehensive provisions for all aspects exist.

3. If you fall neither into category 1 nor category 2, but would like to use these documents and/or curricula nonetheless, please also contact the iSAQB e. V. by writing to contact@isaqb.org. You will then be informed about the possibility of acquiring relevant licenses through existing license agreements, allowing you to obtain your desired usage authorizations.

We stress that, as a matter of principle, this curriculum is protected by copyright.

The International Software Architecture Qualification Board e. V. (iSAQB® e. V.) has exclusive entitlement to these copyrights.

The abbreviation "e. V." is part of the iSAQB's official name and stands for "eingetragener Verein" (registered association), which describes its status as a legal entity according to German law.
 
