// tag::FEEDBACK[]
:filename: what-to-expect-of-this-module.adoc
include::config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::REMARK[]
[IMPORTANT]
====
Bitte diese Datei mit Ueberschrift 3. Ordnung beginnen, damit das Kapitel in
der Struktur unterhalb von "00-preamble/introduction" eingeordnet wird.
====
// end::REMARK[]


// tag::DE[]
=== Was vermittelt das Modul "{curriculum-short}"?

Das Modul präsentiert den Teilnehmerinnen und Teilnehmern {curriculum-name} als …
Am Ende des Moduls kennen die Teilnehmerinnen und Teilnehmer … und können …
// end::DE[]

// tag::EN[]
=== Was does the module "{curriculum-short}" convey?

The module presents {curriculum-short} to the participants …
At the end of the module, the participants know … and are able to …
// end::EN[]

// tag::REMARK[]
[IMPORTANT]
====
Hier bitte das Modul bzw. dessen Lerninhalte zusammenfassend in 5-8 Sätzen beschreiben. Dabei `{curriculum-name}`
nicht entfernen, beim Zusammenbauen wird dieser Platzhalter mit dem Modulnamen ersetzt.
====
// end::REMARK[]
